name: Compress and Deploy

on: 
  push: 
    branches: 
      - main 

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Compressing repository
        run: |
          echo "Compressing repository to emtc.tar..."
          tar --exclude=emct.tar -cf emct.tar .
          echo "Compressing repository to emtc.tar.gz..."
          gzip emct.tar
          echo "Repository compressed to emtc.tar.gz..."

      - name: Install AWS CLI
        run: |
          apt-get update && apt-get install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-s3-bucket: ${{ secrets.S3_BUCKET_NAME }}

      - name: Upload compressed file to S3
        run: |
          echo "Uploading compressed file to S3 bucket..."
          aws s3 cp emct.tar.gz s3://${{ secrets.S3_BUCKET_NAME_CWC }} --metadata "version-id={{ github.run_number }}"
          echo "Upload complete"

      - name: Fetching ssh key from S3
        run: |
          echo "Fetching ssh key from S3 bucket..."
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.EC2_SSH_KEY }} .
          echo $S3_BUCKET_NAME
          echo "Download complete"     
          chmod 400 ${{ secrets.EC2_SSH_KEY }}
          
      - name: Connect to EC2 and run commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: ./${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 instance"
            cd /tmp/
            echo "Changed directory to /tmp/"
            echo "Downloading compressed file from S3..."
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME_CWC }}/emct.tar.gz .
            echo "Download complete"
            echo "Changing directory to /var/www/html/EMCT"
            cd /var/www/html/EMCT 
            echo "Extracting compressed file..."
            tar -xzf /tmp/emct.tar.gz
            echo "Extraction complete"
            echo "Setting permissions"
            mcli set_permissions
            echo "Permissions set"
            mcli restart
            echo "Services restarted"

